### ISSUE TITLE
don't show up in the server list

### ISSUE THREAD

**Issue by oliverjdk** [Skungee/ServerInstances#11]
don't know if I have done something wrong but when I create a server it don't come up I the bundgeecord config and the port doesn't change from server to server and i have set auto port thing to true can you plz help

**Comment by TheLimeGlass** [comment]
Is the config.yml open, or in an editor? Are you running bungee, what version? This works on Bungeecord for others so no clue why. Is there a console error? Is Skungee running the latest version on bungee and Spigot?

**Comment by oliverjdk** [comment]
i have the nyeste update of them all
my config: https://pastebin.com/j6F1tkdD
serverinstances config: https://pastebin.com/4CkBYH1M
and i use windows on the computer

**Comment by oliverjdk** [comment]
Hey I still have this problem if I give you remote access to the computer can you then maybe fix it??
you can add my discord Mrsnow#6492

**Comment by TheLimeGlass** [comment]
Related to #3
